In [1]:
import sys
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
cwd = Path.cwd()
project_root = cwd.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
    print('Done!')

Done!

In [3]:
from src.get_data_sample import get_sample_data, DATA_ENDPOINT

In [4]:
params = {
        'from': '2024-07-14T00:00:00Z',
        'to': '2024-07-15T00:00:00Z',
        'format': 'json'
}

sample_data = get_sample_data(endpoint=DATA_ENDPOINT, params=params)

In [5]:
sample_data = pd.DataFrame(sample_data)
sample_data.head()

  recordType             startTime  demand
0         VD  2024-07-14T00:00:00Z   21556
1         VD  2024-07-14T00:05:00Z   21436
2         VD  2024-07-14T00:10:00Z   21391
3         VD  2024-07-14T00:15:00Z   21410
4         VD  2024-07-14T00:20:00Z   21466

In [6]:
sample_data.tail()

    recordType             startTime  demand
284         VD  2024-07-14T23:40:00Z   21332
285         VD  2024-07-14T23:45:00Z   21273
286         VD  2024-07-14T23:50:00Z   21263
287         VD  2024-07-14T23:55:00Z   21334
288         VD  2024-07-15T00:00:00Z   21233

In [7]:
sample_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    str
 2   demand      289 non-null    int64
dtypes: int64(1), str(2)
memory usage: 6.9 KB

In [8]:
sample_data['startTime'] = pd.to_datetime(sample_data['startTime'])

In [9]:
sample_data.head()

  recordType                 startTime  demand
0         VD 2024-07-14 00:00:00+00:00   21556
1         VD 2024-07-14 00:05:00+00:00   21436
2         VD 2024-07-14 00:10:00+00:00   21391
3         VD 2024-07-14 00:15:00+00:00   21410
4         VD 2024-07-14 00:20:00+00:00   21466

In [10]:
sample_data = sample_data.sort_values(by='startTime')

In [11]:
sample_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    datetime64[us, UTC]
 2   demand      289 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 6.9 KB

check time covarage

In [12]:
sample_data['startTime'].min(), sample_data['startTime'].max()

(Timestamp('2024-07-14 00:00:00+0000', tz='UTC'),
 Timestamp('2024-07-15 00:00:00+0000', tz='UTC'))

In [13]:
(24 * 60) / (5)

288.0

There should be 288 records and the data has 289 records so i don't think there are any missing records.

check duplication

In [14]:
start = sample_data['startTime'].min()
start

Timestamp('2024-07-14 00:00:00+0000', tz='UTC')

In [15]:
for i in range(len(sample_data)):
    if not sample_data.iloc[i]['startTime'] == start:
        print(f'{i}th row might be a duplicate!')
    start = start + pd.Timedelta(minutes=5)

Nothing got printed so no duplication in the sample.

checking recordType

In [16]:
sample_data['recordType'].value_counts()

recordType
VD    289
Name: count, dtype: int64

## Historical Coverage

In [17]:
params = {
    'from': '2024-07-10T00:00:00Z',
    'to': '2024-07-11T00:00:00Z',
    'format': 'json'
}

tenjuly = get_sample_data(endpoint=DATA_ENDPOINT, params=params)

In [18]:
tenjuly = pd.DataFrame(tenjuly)
tenjuly['startTime'] = pd.to_datetime(tenjuly['startTime'])
tenjuly = tenjuly.sort_values(by='startTime')

In [19]:
tenjuly.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    datetime64[us, UTC]
 2   demand      289 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 6.9 KB

In [20]:
tenjuly['recordType'].value_counts()

recordType
VD    289
Name: count, dtype: int64

In [21]:
tenjuly['startTime'].min(), tenjuly['startTime'].max()

(Timestamp('2024-07-10 00:00:00+0000', tz='UTC'),
 Timestamp('2024-07-11 00:00:00+0000', tz='UTC'))

In [22]:
start = tenjuly['startTime'].min()
start

Timestamp('2024-07-10 00:00:00+0000', tz='UTC')

In [23]:
for i in range(len(tenjuly)):
    if not tenjuly.iloc[i]['startTime'] == start:
        print(f'{i}th row might be a duplicate!')
    start = start + pd.Timedelta(minutes=5)

In [24]:
params = {
    'from': '2024-07-01T00:00:00Z',
    'to': '2024-07-02T00:00:00Z',
    'format': 'json'
}

onejuly = get_sample_data(endpoint=DATA_ENDPOINT, params=params)

In [25]:
onejuly = pd.DataFrame(onejuly)
onejuly['startTime'] = pd.to_datetime(onejuly['startTime'])
onejuly = onejuly.sort_values(by='startTime')

In [26]:
onejuly.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    datetime64[us, UTC]
 2   demand      289 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 6.9 KB

In [27]:
onejuly['recordType'].value_counts()

recordType
VD    289
Name: count, dtype: int64

In [28]:
onejuly['startTime'].min(), onejuly['startTime'].max()

(Timestamp('2024-07-01 00:00:00+0000', tz='UTC'),
 Timestamp('2024-07-02 00:00:00+0000', tz='UTC'))

In [29]:
start = onejuly['startTime'].min()
start

Timestamp('2024-07-01 00:00:00+0000', tz='UTC')

In [30]:
for i in range(len(onejuly)):
    if not onejuly.iloc[i]['startTime'] == start:
        print(f'{i}th row might be a duplicate!')
    start = start + pd.Timedelta(minutes=5)

In [31]:
params = {
    'from': '2023-07-01T00:00:00Z',
    'to': '2023-07-02T00:00:00Z',
    'format': 'json'
}

onejulytt = get_sample_data(endpoint=DATA_ENDPOINT, params=params)

In [32]:
onejulytt = pd.DataFrame(onejulytt)
onejulytt['startTime'] = pd.to_datetime(onejulytt['startTime'])
onejulytt = onejulytt.sort_values(by='startTime')

In [33]:
onejulytt.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    datetime64[us, UTC]
 2   demand      289 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 6.9 KB

In [34]:
onejulytt['recordType'].value_counts()

recordType
VD    289
Name: count, dtype: int64

In [35]:
onejulytt['startTime'].min(), onejulytt['startTime'].max()

(Timestamp('2023-07-01 00:00:00+0000', tz='UTC'),
 Timestamp('2023-07-02 00:00:00+0000', tz='UTC'))

In [36]:
start = onejulytt['startTime'].min()
start

Timestamp('2023-07-01 00:00:00+0000', tz='UTC')

In [37]:
for i in range(len(onejulytt)):
    if not onejulytt.iloc[i]['startTime'] == start:
        print(f'{i}th row might be a duplicate!')
    start = start + pd.Timedelta(minutes=5)

## Timezone and daylight-saving checks.

In [39]:
sample_data['time_london'] = sample_data['startTime'].dt.tz_convert('Europe/London')

In [40]:
sample_data[['startTime', 'time_london']].head()

                  startTime               time_london
0 2024-07-14 00:00:00+00:00 2024-07-14 01:00:00+01:00
1 2024-07-14 00:05:00+00:00 2024-07-14 01:05:00+01:00
2 2024-07-14 00:10:00+00:00 2024-07-14 01:10:00+01:00
3 2024-07-14 00:15:00+00:00 2024-07-14 01:15:00+01:00
4 2024-07-14 00:20:00+00:00 2024-07-14 01:20:00+01:00

In [42]:
sample_data.shape

(289, 4)

Creating sequences in london local time and UTC

In [37]:
ordinary_london_day = pd.date_range(
    start='2024-03-30 00:00',
    end='2024-03-31 00:00',
    freq='5min',
    tz='Europe/London',
    inclusive='left'
)

In [38]:
len(ordinary_london_day)

288

In [39]:
spring_day = pd.date_range(
    start='2024-03-31 00:00',
    end='2024-04-01 00:00',
    freq='5min',
    tz='Europe/London',
    inclusive='left'
)

autumn_day = pd.date_range(
    start='2024-10-27 00:00',
    end='2024-10-28 00:00',
    freq='5min',
    tz='Europe/London',
    inclusive='left'
)

In [40]:
len(ordinary_london_day), len(spring_day), len(autumn_day)

(288, 276, 300)

In [41]:
ordinary_london_day.is_unique, spring_day.is_unique, autumn_day.is_unique

(True, True, True)

In [42]:
autumn_day[0:40]

DatetimeIndex(['2024-10-27 00:00:00+01:00', '2024-10-27 00:05:00+01:00',
               '2024-10-27 00:10:00+01:00', '2024-10-27 00:15:00+01:00',
               '2024-10-27 00:20:00+01:00', '2024-10-27 00:25:00+01:00',
               '2024-10-27 00:30:00+01:00', '2024-10-27 00:35:00+01:00',
               '2024-10-27 00:40:00+01:00', '2024-10-27 00:45:00+01:00',
               '2024-10-27 00:50:00+01:00', '2024-10-27 00:55:00+01:00',
               '2024-10-27 01:00:00+01:00', '2024-10-27 01:05:00+01:00',
               '2024-10-27 01:10:00+01:00', '2024-10-27 01:15:00+01:00',
               '2024-10-27 01:20:00+01:00', '2024-10-27 01:25:00+01:00',
               '2024-10-27 01:30:00+01:00', '2024-10-27 01:35:00+01:00',
               '2024-10-27 01:40:00+01:00', '2024-10-27 01:45:00+01:00',
               '2024-10-27 01:50:00+01:00', '2024-10-27 01:55:00+01:00',
               '2024-10-27 01:00:00+00:00', '2024-10-27 01:05:00+00:00',
               '2024-10-27 01:10:00+00:00', '2024-10-27 01:15:00+00:00',
               '2024-10-27 01:20:00+00:00', '2024-10-27 01:25:00+00:00',
               '2024-10-27 01:30:00+00:00', '2024-10-27 01:35:00+00:00',
               '2024-10-27 01:40:00+00:00', '2024-10-27 01:45:00+00:00',
               '2024-10-27 01:50:00+00:00', '2024-10-27 01:55:00+00:00',
               '2024-10-27 02:00:00+00:00', '2024-10-27 02:05:00+00:00',
               '2024-10-27 02:10:00+00:00', '2024-10-27 02:15:00+00:00'],
              dtype='datetime64[us, Europe/London]', freq='5min')

In [43]:
spring_day[0:40]

DatetimeIndex(['2024-03-31 00:00:00+00:00', '2024-03-31 00:05:00+00:00',
               '2024-03-31 00:10:00+00:00', '2024-03-31 00:15:00+00:00',
               '2024-03-31 00:20:00+00:00', '2024-03-31 00:25:00+00:00',
               '2024-03-31 00:30:00+00:00', '2024-03-31 00:35:00+00:00',
               '2024-03-31 00:40:00+00:00', '2024-03-31 00:45:00+00:00',
               '2024-03-31 00:50:00+00:00', '2024-03-31 00:55:00+00:00',
               '2024-03-31 02:00:00+01:00', '2024-03-31 02:05:00+01:00',
               '2024-03-31 02:10:00+01:00', '2024-03-31 02:15:00+01:00',
               '2024-03-31 02:20:00+01:00', '2024-03-31 02:25:00+01:00',
               '2024-03-31 02:30:00+01:00', '2024-03-31 02:35:00+01:00',
               '2024-03-31 02:40:00+01:00', '2024-03-31 02:45:00+01:00',
               '2024-03-31 02:50:00+01:00', '2024-03-31 02:55:00+01:00',
               '2024-03-31 03:00:00+01:00', '2024-03-31 03:05:00+01:00',
               '2024-03-31 03:10:00+01:00', '2024-03-31 03:15:00+01:00',
               '2024-03-31 03:20:00+01:00', '2024-03-31 03:25:00+01:00',
               '2024-03-31 03:30:00+01:00', '2024-03-31 03:35:00+01:00',
               '2024-03-31 03:40:00+01:00', '2024-03-31 03:45:00+01:00',
               '2024-03-31 03:50:00+01:00', '2024-03-31 03:55:00+01:00',
               '2024-03-31 04:00:00+01:00', '2024-03-31 04:05:00+01:00',
               '2024-03-31 04:10:00+01:00', '2024-03-31 04:15:00+01:00'],
              dtype='datetime64[us, Europe/London]', freq='5min')

In [44]:
spring_utc = spring_day.tz_convert('UTC')
autumn_utc = autumn_day.tz_convert('UTC')
ordinary_utc = ordinary_london_day.tz_convert('UTC')

In [45]:
len(ordinary_utc), len(spring_utc), len(autumn_utc)

(288, 276, 300)

In [55]:
ordinary_utc.is_unique, spring_utc.is_unique, autumn_utc.is_unique

(True, True, True)

In [57]:
gaps = spring_utc.to_series().diff()
gaps.head()

2024-03-31 00:00:00+00:00               NaT
2024-03-31 00:05:00+00:00   0 days 00:05:00
2024-03-31 00:10:00+00:00   0 days 00:05:00
2024-03-31 00:15:00+00:00   0 days 00:05:00
2024-03-31 00:20:00+00:00   0 days 00:05:00
Freq: 5min, dtype: timedelta64[us]

In [58]:
for name, sequence in [
    ('ordinary', ordinary_utc),
    ('spring', spring_utc),
    ('autumn', autumn_utc),
]:
    print(name)
    print(sequence.to_series().diff().dropna().value_counts())

ordinary
0 days 00:05:00    287
Name: count, dtype: int64
spring
0 days 00:05:00    275
Name: count, dtype: int64
autumn
0 days 00:05:00    299
Name: count, dtype: int64

In [61]:
spring_day[0:40]

DatetimeIndex(['2024-03-31 00:00:00+00:00', '2024-03-31 00:05:00+00:00',
               '2024-03-31 00:10:00+00:00', '2024-03-31 00:15:00+00:00',
               '2024-03-31 00:20:00+00:00', '2024-03-31 00:25:00+00:00',
               '2024-03-31 00:30:00+00:00', '2024-03-31 00:35:00+00:00',
               '2024-03-31 00:40:00+00:00', '2024-03-31 00:45:00+00:00',
               '2024-03-31 00:50:00+00:00', '2024-03-31 00:55:00+00:00',
               '2024-03-31 02:00:00+01:00', '2024-03-31 02:05:00+01:00',
               '2024-03-31 02:10:00+01:00', '2024-03-31 02:15:00+01:00',
               '2024-03-31 02:20:00+01:00', '2024-03-31 02:25:00+01:00',
               '2024-03-31 02:30:00+01:00', '2024-03-31 02:35:00+01:00',
               '2024-03-31 02:40:00+01:00', '2024-03-31 02:45:00+01:00',
               '2024-03-31 02:50:00+01:00', '2024-03-31 02:55:00+01:00',
               '2024-03-31 03:00:00+01:00', '2024-03-31 03:05:00+01:00',
               '2024-03-31 03:10:00+01:00', '2024-03-31 03:15:00+01:00',
               '2024-03-31 03:20:00+01:00', '2024-03-31 03:25:00+01:00',
               '2024-03-31 03:30:00+01:00', '2024-03-31 03:35:00+01:00',
               '2024-03-31 03:40:00+01:00', '2024-03-31 03:45:00+01:00',
               '2024-03-31 03:50:00+01:00', '2024-03-31 03:55:00+01:00',
               '2024-03-31 04:00:00+01:00', '2024-03-31 04:05:00+01:00',
               '2024-03-31 04:10:00+01:00', '2024-03-31 04:15:00+01:00'],
              dtype='datetime64[us, Europe/London]', freq='5min')

In [62]:
spring_utc[0:40]

DatetimeIndex(['2024-03-31 00:00:00+00:00', '2024-03-31 00:05:00+00:00',
               '2024-03-31 00:10:00+00:00', '2024-03-31 00:15:00+00:00',
               '2024-03-31 00:20:00+00:00', '2024-03-31 00:25:00+00:00',
               '2024-03-31 00:30:00+00:00', '2024-03-31 00:35:00+00:00',
               '2024-03-31 00:40:00+00:00', '2024-03-31 00:45:00+00:00',
               '2024-03-31 00:50:00+00:00', '2024-03-31 00:55:00+00:00',
               '2024-03-31 01:00:00+00:00', '2024-03-31 01:05:00+00:00',
               '2024-03-31 01:10:00+00:00', '2024-03-31 01:15:00+00:00',
               '2024-03-31 01:20:00+00:00', '2024-03-31 01:25:00+00:00',
               '2024-03-31 01:30:00+00:00', '2024-03-31 01:35:00+00:00',
               '2024-03-31 01:40:00+00:00', '2024-03-31 01:45:00+00:00',
               '2024-03-31 01:50:00+00:00', '2024-03-31 01:55:00+00:00',
               '2024-03-31 02:00:00+00:00', '2024-03-31 02:05:00+00:00',
               '2024-03-31 02:10:00+00:00', '2024-03-31 02:15:00+00:00',
               '2024-03-31 02:20:00+00:00', '2024-03-31 02:25:00+00:00',
               '2024-03-31 02:30:00+00:00', '2024-03-31 02:35:00+00:00',
               '2024-03-31 02:40:00+00:00', '2024-03-31 02:45:00+00:00',
               '2024-03-31 02:50:00+00:00', '2024-03-31 02:55:00+00:00',
               '2024-03-31 03:00:00+00:00', '2024-03-31 03:05:00+00:00',
               '2024-03-31 03:10:00+00:00', '2024-03-31 03:15:00+00:00'],
              dtype='datetime64[us, UTC]', freq='5min')

Actual API records check clock-change days

In [10]:
start_london = pd.Timestamp('2024-03-31 00:00', tz='Europe/London')
end_london = pd.Timestamp('2024-04-01 00:00', tz='Europe/London')

start_utc = start_london.tz_convert('UTC')
end_utc = end_london.tz_convert('UTC')

In [11]:
start_utc, end_utc

(Timestamp('2024-03-31 00:00:00+0000', tz='UTC'),
 Timestamp('2024-03-31 23:00:00+0000', tz='UTC'))

In [12]:
params = {
    'from': start_utc.isoformat(),
    'to': end_utc.isoformat(),
    'format': 'json'
}

print(params)

{'from': '2024-03-31T00:00:00+00:00', 'to': '2024-03-31T23:00:00+00:00', 'format': 'json'}

In [18]:
spring_api = get_sample_data(
    endpoint=DATA_ENDPOINT,
    params=params
)

spring_api = pd.DataFrame(spring_api)
spring_api['startTime'] = pd.to_datetime(spring_api['startTime'], utc=True)
spring_api = spring_api.loc[(spring_api['startTime'] >= start_utc) & (spring_api['startTime'] < end_utc)].sort_values(by='startTime')

In [19]:
spring_api.shape

(276, 3)

In [24]:
start_london = pd.Timestamp('2024-10-27 00:00', tz='Europe/London')
end_london = pd.Timestamp('2024-10-28 00:00', tz='Europe/London')

start_utc = start_london.tz_convert('UTC')
end_utc = end_london.tz_convert('UTC')

In [25]:
start_utc, end_utc

(Timestamp('2024-10-26 23:00:00+0000', tz='UTC'),
 Timestamp('2024-10-28 00:00:00+0000', tz='UTC'))

In [29]:
params = {
    'from': start_utc.isoformat(),
    'to': end_utc.isoformat(),
    'format': 'json'    
}

autumn_api = get_sample_data(
    endpoint=DATA_ENDPOINT,
    params=params
)

In [30]:
autumn_api = pd.DataFrame(autumn_api)
autumn_api['startTime'] = pd.to_datetime(autumn_api['startTime'], utc=True)
autumn_api = autumn_api.loc[(autumn_api['startTime'] >= start_utc) & (autumn_api['startTime'] < end_utc)].sort_values(by='startTime')

In [31]:
autumn_api.shape

(300, 3)

In [32]:
spring_api['recordType'].value_counts()

recordType
VD    276
Name: count, dtype: int64

In [33]:
autumn_api['recordType'].value_counts()

recordType
VD    300
Name: count, dtype: int64

In [47]:
expected = spring_utc
actual = pd.DatetimeIndex(spring_api['startTime'])

In [50]:
missing = expected.difference(actual)
unexpected = actual.difference(expected)

In [54]:
print('Spring')
print('Missing:', missing)
print('Unexpected:', unexpected)

Spring
Missing: DatetimeIndex([], dtype='datetime64[us, UTC]', freq='5min')
Unexpected: DatetimeIndex([], dtype='datetime64[us, UTC]', freq=None)

In [53]:
expected = autumn_utc
actual = pd.DatetimeIndex(autumn_api['startTime'])

In [55]:
missing = expected.difference(actual)
unexpected = actual.difference(expected)

In [56]:
print('Autumn')
print('Missing:', missing)
print('Unexpected:', unexpected)

Autumn
Missing: DatetimeIndex([], dtype='datetime64[us, UTC]', freq='5min')
Unexpected: DatetimeIndex([], dtype='datetime64[us, UTC]', freq=None)

In [57]:
autumn_api.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  300 non-null    str
 1   startTime   300 non-null    datetime64[us, UTC]
 2   demand      300 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 7.2 KB

In [58]:
spring_api.info()

<class 'pandas.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  276 non-null    str
 1   startTime   276 non-null    datetime64[us, UTC]
 2   demand      276 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 6.6 KB