In [1]:
import sys
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
cwd = Path.cwd()
project_root = cwd.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
    print('Done!')

Done!

In [3]:
from src.get_data_sample import get_sample_data, DATA_ENDPOINT

In [4]:
params = {
        'from': '2024-07-14T00:00:00Z',
        'to': '2024-07-15T00:00:00Z',
        'format': 'json'
}

sample_data = get_sample_data(endpoint=DATA_ENDPOINT, params=params)

In [5]:
sample_data = pd.DataFrame(sample_data)
sample_data.head()

  recordType             startTime  demand
0         VD  2024-07-14T00:00:00Z   21556
1         VD  2024-07-14T00:05:00Z   21436
2         VD  2024-07-14T00:10:00Z   21391
3         VD  2024-07-14T00:15:00Z   21410
4         VD  2024-07-14T00:20:00Z   21466

In [6]:
sample_data.tail()

    recordType             startTime  demand
284         VD  2024-07-14T23:40:00Z   21332
285         VD  2024-07-14T23:45:00Z   21273
286         VD  2024-07-14T23:50:00Z   21263
287         VD  2024-07-14T23:55:00Z   21334
288         VD  2024-07-15T00:00:00Z   21233

In [7]:
sample_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    str
 2   demand      289 non-null    int64
dtypes: int64(1), str(2)
memory usage: 6.9 KB

In [8]:
sample_data['startTime'] = pd.to_datetime(sample_data['startTime'])

In [9]:
sample_data.head()

  recordType                 startTime  demand
0         VD 2024-07-14 00:00:00+00:00   21556
1         VD 2024-07-14 00:05:00+00:00   21436
2         VD 2024-07-14 00:10:00+00:00   21391
3         VD 2024-07-14 00:15:00+00:00   21410
4         VD 2024-07-14 00:20:00+00:00   21466

In [10]:
sample_data = sample_data.sort_values(by='startTime')

In [11]:
sample_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    datetime64[us, UTC]
 2   demand      289 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 6.9 KB

check time covarage

In [12]:
sample_data['startTime'].min(), sample_data['startTime'].max()

(Timestamp('2024-07-14 00:00:00+0000', tz='UTC'),
 Timestamp('2024-07-15 00:00:00+0000', tz='UTC'))

In [13]:
(24 * 60) / (5)

288.0

There should be 288 records and the data has 289 records so i don't think there are any missing records.

check duplication

In [14]:
start = sample_data['startTime'].min()
start

Timestamp('2024-07-14 00:00:00+0000', tz='UTC')

In [15]:
for i in range(len(sample_data)):
    if not sample_data.iloc[i]['startTime'] == start:
        print(f'{i}th row might be a duplicate!')
    start = start + pd.Timedelta(minutes=5)

Nothing got printed so no duplication in the sample.

checking recordType

In [16]:
sample_data['recordType'].value_counts()

recordType
VD    289
Name: count, dtype: int64

## Historical Coverage

In [17]:
params = {
    'from': '2024-07-10T00:00:00Z',
    'to': '2024-07-11T00:00:00Z',
    'format': 'json'
}

tenjuly = get_sample_data(endpoint=DATA_ENDPOINT, params=params)

In [18]:
tenjuly = pd.DataFrame(tenjuly)
tenjuly['startTime'] = pd.to_datetime(tenjuly['startTime'])
tenjuly = tenjuly.sort_values(by='startTime')

In [19]:
tenjuly.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    datetime64[us, UTC]
 2   demand      289 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 6.9 KB

In [20]:
tenjuly['recordType'].value_counts()

recordType
VD    289
Name: count, dtype: int64

In [21]:
tenjuly['startTime'].min(), tenjuly['startTime'].max()

(Timestamp('2024-07-10 00:00:00+0000', tz='UTC'),
 Timestamp('2024-07-11 00:00:00+0000', tz='UTC'))

In [22]:
start = tenjuly['startTime'].min()
start

Timestamp('2024-07-10 00:00:00+0000', tz='UTC')

In [23]:
for i in range(len(tenjuly)):
    if not tenjuly.iloc[i]['startTime'] == start:
        print(f'{i}th row might be a duplicate!')
    start = start + pd.Timedelta(minutes=5)

In [24]:
params = {
    'from': '2024-07-01T00:00:00Z',
    'to': '2024-07-02T00:00:00Z',
    'format': 'json'
}

onejuly = get_sample_data(endpoint=DATA_ENDPOINT, params=params)

In [25]:
onejuly = pd.DataFrame(onejuly)
onejuly['startTime'] = pd.to_datetime(onejuly['startTime'])
onejuly = onejuly.sort_values(by='startTime')

In [26]:
onejuly.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    datetime64[us, UTC]
 2   demand      289 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 6.9 KB

In [27]:
onejuly['recordType'].value_counts()

recordType
VD    289
Name: count, dtype: int64

In [28]:
onejuly['startTime'].min(), onejuly['startTime'].max()

(Timestamp('2024-07-01 00:00:00+0000', tz='UTC'),
 Timestamp('2024-07-02 00:00:00+0000', tz='UTC'))

In [29]:
start = onejuly['startTime'].min()
start

Timestamp('2024-07-01 00:00:00+0000', tz='UTC')

In [30]:
for i in range(len(onejuly)):
    if not onejuly.iloc[i]['startTime'] == start:
        print(f'{i}th row might be a duplicate!')
    start = start + pd.Timedelta(minutes=5)

In [31]:
params = {
    'from': '2023-07-01T00:00:00Z',
    'to': '2023-07-02T00:00:00Z',
    'format': 'json'
}

onejulytt = get_sample_data(endpoint=DATA_ENDPOINT, params=params)

In [32]:
onejulytt = pd.DataFrame(onejulytt)
onejulytt['startTime'] = pd.to_datetime(onejulytt['startTime'])
onejulytt = onejulytt.sort_values(by='startTime')

In [33]:
onejulytt.info()

<class 'pandas.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   recordType  289 non-null    str
 1   startTime   289 non-null    datetime64[us, UTC]
 2   demand      289 non-null    int64
dtypes: datetime64[us, UTC](1), int64(1), str(1)
memory usage: 6.9 KB

In [34]:
onejulytt['recordType'].value_counts()

recordType
VD    289
Name: count, dtype: int64

In [35]:
onejulytt['startTime'].min(), onejulytt['startTime'].max()

(Timestamp('2023-07-01 00:00:00+0000', tz='UTC'),
 Timestamp('2023-07-02 00:00:00+0000', tz='UTC'))

In [36]:
start = onejulytt['startTime'].min()
start

Timestamp('2023-07-01 00:00:00+0000', tz='UTC')

In [37]:
for i in range(len(onejulytt)):
    if not onejulytt.iloc[i]['startTime'] == start:
        print(f'{i}th row might be a duplicate!')
    start = start + pd.Timedelta(minutes=5)